query EventList(
  $categoryIds: [ID!]!
  $cityId: ID!
  $sort: String
  $start: Int
) {
  eventList(
    categoryIds: $categoryIds
    cityIds: [$cityId]
    sort: $sort
    start: $start
  ) {
    events {
      # currency
      eventDate {
        value
      }
      images {
        standard {
          url
        }
      }
      name
      priceRanges {
        includingTicketFees {
          min
        }
      }
      properties {
        seats_available
        sold_out
      }
      url
    }
    hasMore
  }
}
