query EventsPage($start: Int!) {
  # $city: String!, $classification: ID
  eventsPage(start: $start) {
    # city: $city, classification: $classification
    events {
      name
      url
      images {
        standard {
          url
        }
      }
    }
    hasMore
  }
}
