query MostRelevantEvents($city: String!) {
    mostRelevantEvents(city: $city) {
        name
        dates {
            start {
                localDate
                localTime
            }
        }
        images {
            url
            width
        }
    }
}
