query mostRelevantEvents {
    mostRelevantEvents {
        name
        dates {
            start {
                localDate
                localTime
            }
        }
        image {
            url
        }
    }
}
